language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install
  - composer require --dev

script: phpunit --coverage-text

notifications:
  email:
    - benoit.alessandroni@gmail.com
