language: php


php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer --dev install

script:
- phpunit --coverage-text

notifications:
  email:
    - benoit.alessandroni@gmail.com
